### ISSUE TITLE
lenddo_clients.Score is not a function

### ISSUE THREAD

**Issue by ajith92** [Lenddo/node-lenddo#1]
I am following the doc https://lenddo.com/documentation/nodejs_sdk.html, 

var lenddo_clients = require('lenddo').clients;
var ScoreService = lenddo_clients.Score;
var client_instance = new ScoreService(id, secret);

I get the error mentioned in the title, i.e TypeError: lenddo_clients.Score is not a function

When I see the lenddo_client on console, Score is undefined

**Comment by Howard3** [comment]
Hello ajith, 

Thank you for the detailed report. I see what is wrong in the code and will submit a patch today around 3pm GMT+8. 

Best Regards, 
Howard

**Comment by Howard3** [comment]
Thank you for your bug report. v1.7.2 has been released now and should resolve the highlighted issue!
